#!/bin/sh

# `ld -r` for Cosmo.

set -eu

COSMIZE=${1}
shift

# For Cosmo builds, this section is auto-generated by `gcc` when
# `-fpatchable-function-entry=...` is used for `--ftrace` support.
# The section is actually unused, and will eventually be removed by
# the Cosmo linker script when linking the final binary.
# However, we need to remove them right here, otherwise a relocation
# corresponding to one of the entries might reference a COMDAT group
# from a C++ file (for example, in XeTeX) that is discarded on `ld -r`.
# This leads to a linker warning in `ld.lld` and an error in `ld.bfd`.
AFTER_OUT=0
for arg
do
    if [ "${arg}" = "${arg#-}" -a $AFTER_OUT -eq 0 ]
    then
        ${COSMIZE} objcopy --remove-section=__patchable_function_entries "${arg}"
    fi
    if [ "${arg}" = "-o" ]
    then
        AFTER_OUT=1
    else
        AFTER_OUT=0
    fi
done

${COSMIZE} ld -r $@
