name: bench-native

on: 
  workflow_dispatch:
    inputs:
      busytexreleasetag:
        description: 'busytex release tag'
        required: false
        default: 'build_native_418c9bc5edfd99fdb560cff956d3f10d3e598bcf_6949768401_1'

env:
  MAKE_PARALLELISM: -j2
  BENCHSETURLS: https://github.com/busytex/busytex/releases/download/tectonicbenchset/arXiv_src_1702_001.tar

jobs:

  bench-native:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Download benchset
        run: | 
          wget ${{env.BENCHSETURLS}}
          mkdir -p ./benchset/tar
          tar -xf arXiv_src_1702_001.tar --directory ./benchset/
          for f in ./benchset/*/*.gz; do
            mkdir -p ./benchset/tar/$(basename $f)
            gzip -c -d $f > ./benchset/tar/$(basename $f)/$(basename $f).tex
            tar -xf ./benchset/tar/$(basename $f)/$(basename $f).tex --directory=./benchset/tar/$(basename $f) && rm ./benchset/tar/$(basename $f)/$(basename $f).tex || true
          done

      - name: List benchset
        run: find ./benchset/tar
      
      - name: Download native binaries
        run:  make URLRELEASE=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ github.event.inputs.busytexreleasetag }} download-native
      
      - name: Smoke native
        run:  make smoke-native
      
      - name: Test native 
        run: |
            make source/texmfrepo.txt
            make build/texlive-basic.txt
            make dist-native
            sh example/example.sh
      
      - name: Bench
        run: |
            find ./benchset/tar/ -mindepth 1 -maxdepth 1 
            find ./benchset/tar/ -mindepth 1 -maxdepth 1 -exec python busytexmk.py --DIST ./dist-native --busytex ./dist-native/busytex -i {} ';'
            #python busytexmk.py --driver pdflatex -i ./benchset/tar/1702.00331.gz --tex-relative-path ./Arxiv_SiEr_Celebrano.tex --DIST ./dist-native --busytex ./dist-native/busytex
