name: bench-native

on: 
  workflow_dispatch:
    inputs:
      busytexreleasetag:
        description: 'busytex release tag'
        required: false
        default: 'build_native_418c9bc5edfd99fdb560cff956d3f10d3e598bcf_6949768401_1'

env:
  MAKE_PARALLELISM: -j2
  BENCHSETURLS: https://github.com/busytex/busytex/releases/download/tectonicbenchset/arXiv_src_1702_001.tar

jobs:

  bench-native:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Download native binaries
        run:  make URLRELEASE=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ github.event.inputs.busytexreleasetag }} download-native
      
      - name: Smoke native
        run:  make smoke-native
      
      - name: Test native 
        run: |
            make source/texmfrepo.txt
            make build/texlive-basic.txt # build/texlive-full.txt
            make dist-native
            sh example/example.sh
            #rm -rf dist-native/texlive
            #ln -s $PWD/build/texlive-full dist-native/texlive
            #rm -rf source/texmfrepo build/texlive-basic
        env:
            MAKEFLAGS: ${{env.MAKE_PARALLELISM}}

      - name: Download benchset
        run: | 
          wget ${{env.BENCHSETURLS}}
          mkdir -p ./benchset/tar
          tar -xf arXiv_src_1702_001.tar --directory ./benchset/ && rm arXiv_src_1702_001.tar 
          for f in ./benchset/*/*.gz; do
            mkdir -p ./benchset/tar/$(basename $f)
            gzip -c -d $f > ./benchset/tar/$(basename $f)/$(basename $f).tex && rm $f
            tar -xf ./benchset/tar/$(basename $f)/$(basename $f).tex --directory=./benchset/tar/$(basename $f) && rm ./benchset/tar/$(basename $f)/$(basename $f).tex || true
          done

      - name: List benchset
        run: find ./benchset/tar
      
      - name: Bench
        run: |
            find ./benchset/tar/ -type d -mindepth 1 -maxdepth 1 -exec python busytexmk.py --driver pdflatex --bibtex --DIST ./dist-native --busytex ./dist-native/busytex -i {} --log {}/busytexmk.log ';' 1> bench.log 2> bencherr.log
            #cat bench.log bencherr.log
            find ./benchset/tar/ -name busytexmk.log
            mkdir OK FAIL
            grep   OK bench.log | while read dirname remainder; do cp $dirname/busytexmk.log   OK/$(basename $dirname)_busytexmk.log || true; done
            grep FAIL bench.log | while read dirname remainder; do cp $dirname/busytexmk.log FAIL/$(basename $dirname)_busytexmk.log || true; done
            echo TOTAL: $(wc -l bench.log) OK: $(grep OK bench.log | wc -l) FAIL: $(grep FAIL bench.log | wc -l)

      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            bench.log
            OK/*busytexmk.log
            FAIL/*busytexmk.log
            ./benchset/tar/*/busytexmk.log
